### ISSUE TITLE
MarkDuplicates missing in QC metrics

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#103]
It seems that MarkDuplicates is missing from qc metrics file in the new update

We also would like the number of reads for each lane/fastq-file-pair to accompany the reads mapped number - otherwise it's difficult to calculate the value on a per-sample basis

ping @b4ckm4n

**Comment by henrikstranneheim** [comment]
Fixed MarkDuplicates in new hotfix. Try it out and see if it works.

"We also would like the number of reads for each lane/fastq-file-pair to accompany the reads mapped number - otherwise it's difficult to calculate the value on a per-sample basis"
Was this a MIP issue?  If so please open up a seperate issue and explain more. Closing issue for now!
