### ISSUE TITLE
Record version numbers of all used software in the pipeline

### ISSUE THREAD

**Issue by ingkebil** [henrikstranneheim/MIP#105]
It would be nice to not only check that the software if present and executable, but also record the version number into the mip-log.

This doesn't have to be a dynamic check, but can simply be a yaml file that has all version recorded and needs to be updated manually. These can then be printed out along side the software name when you make the check whether or not the software is present.

**Comment by henrikstranneheim** [comment]
The software versions that are used for a particular analysis are written into qcmetrics.yaml and qc_sampleInfo.yaml (dynamically).

I have added the install script to the conda env upon installation so that if you want to know what version was installed alongside your particular version of MIP. 
You type:
$install.pl -ppd
preferShell 0
pip python-Levenshtein: 0.12.0
pip chanjo: 3.4.1
pip cosmid: 0.4.9.1
pip genmod: 3.5.2
bioCondaSnpeffPatch -0
condaUpDate 0
vepAssemblies: GRCh37
picardTools 2.3.0
plink2 160316
bioCondaPicardPatch -0
selectPrograms:
vcfTools 0.1.14
perl 5.18.2
bioConda vt: 2015.11.10
bioConda bwakit: 0.7.12
bioConda samtools: 1.3
bioConda mosaik: 2.2.26
bioConda manta: 0.29.6
bioConda bedtools: 2.25.0
bioConda gcc: 4.8.5
bioConda htslib: 1.3
bioConda bcftools: 1.3
bioConda freebayes: 1.0.2
bioConda picard: 2.3.0
bioConda plink2: 1.90b3.35
bioConda bwa: 0.7.13
bioConda delly: 0.7.2
bioConda multiqc: 0.6
bioConda sambamba: 0.6.1
bioConda fastqc: 0.11.5
bioConda cramtools: 3.0.b47
bioConda snpeff: 4.2
bioConda vcfanno: 0.0.11
sambamba 0.6.1
variantEffectPredictor 84
condaPath /home/henrik.stranneheim/miniconda
vt gitRepo
variantEffectPredictorPlugin UpDownDistance,LoFtool,LoF
CNVnator 0.3.2
bioCondaBwakitPatch -0
perlInstall 0
snpEffGenomeVersions: GRCh37.75
MIPScripts Your current MIP version
bedTools 2.25.0
condaEnvironment mip
bioCondaMantaPatch -0
perlModules: Modern::Perl IPC::System::Simple Path::Iterator::Rule YAML Log::Log4perl Set::IntervalTree Net::SSLeay LWP::Simple LWP::Protocol::https Archive::Zip Archive::Extract DBI JSON DBD::mysql CGI Sereal::Encoder Sereal::Decoder Bio::Root::Version Module::Build
snpEff v4_2
FindTranslocations 0
vepDirectoryCache /home/henrik.stranneheim/miniconda/envs/mip/ensembl-tools-release-84/cache
noUpdate 0

**Comment by ingkebil** [comment]
Sometimes we are unsure what versions MIP is run with. This is especially true when we are upgrading independent parts as a hotfix and we now need to log this by filing a deviation. This makes looking up with what versions MIP ran a lot more tedious.
Also: GATK is missing from above output ;)

Anyway, my request stands. It would be really nice if the versioning information could be logged for each MIP run.

**Comment by henrikstranneheim** [comment]
The MIP version is always recorded in the mip_log, qc_sampleInfo.yaml for each run. 
You can do mip -v for your current version.

GATK is missing because you need a license to install it. However, the GATK version is recorded in mip_log (as a complete path to the GATK dir), qcmetrics.yaml (version) and qc_sampleInfo.yaml (version) for each run.

"Anyway, my request stands. It would be really nice if the versioning information could be logged for each MIP run."
Like I said it already is: in qcmetrics.yaml and qc_sampleInfo.yaml. Not sure what more info you actually want.

**Comment by ingkebil** [comment]
No no :) I'm still talking about all the software MIP is relying on, not only the MIP version. I want to have the version of all software logged in the mip_log. You're checking if they're installed anyway, it would be nice to have them listed with version.

To keep on going with GATK, I don't find the path/version in the mip_log. I do find the version number in qc_sampleInfo.yaml however. So yay that! :)

I did a random check, took vcftools and snpeff, but cannot find in any of the files you mentioned the versions of those softwares used in a MIP run.

**Comment by henrikstranneheim** [comment]
Added vcfTools and Plink2 versions to qcmetrics as they were missing. SnpEff was there already.

The rest is solved.
