### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#106]
I've noticed as I more around MIP output for testing etc. that the idea of storing absolute paths to resources can become an obstacle. If you move MIP output now -- all the references in config and sample info no longer make sense.

Would it be possible instead to base all paths around a central "root path" so you'd only have to update that one if you move the output? Or perhaps make all paths relative to the root of the analysis folder for example?

What benefits do you see with absolute paths vs. relative paths?

**Comment by henrikstranneheim** [comment]
"all the references in config and sample info no longer make sense" - They are supposed to be the record of what was actually analysed, with what and where, so that is the intent. 

Not sure what you are aiming to do, but you can:
 - change the path to the MIP reference directory using "--referencesDir" flag
 - redirect the output using "--outDataDir"
 - change the path to the analysis in the config using "clusterConstantPath" and/or "analysisConstantPath".

**Comment by robinandeer** [comment]
I think we'll implement another layer so we can work with absolute paths
