### ISSUE TITLE
Missing version for genmod for WGS analysis

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#118]
Strange case where Genmod version info doesn't get filled in, in qc metrics:

/mnt/hds/proj/bioinfo/MIP_ANALYSIS/customers/cust000/643594-300M/analysis/643594-300M/643594-300M_qc_metrics.yaml

**Comment by henrikstranneheim** [comment]
This is because there is no genmod software tag in the vcf header.

This family is only unaffected which means that MIP will not run:
[WARN] 2016/12/30 11:04:45 MIP_logger - Only unaffected sample in pedigree - skipping genmod 'models', 'score' and 'compound'

MIP will only run genmod annotate, which does not seem to ouput the software tag in the header.

Also analysisrunstatus will fail some tests because some of the genmod output keys are missing in the final vcf. I will see if I can make this dynamically adjusted in future versions.

**Comment by robinandeer** [comment]
okey, thanks!

I updated our software to not expect genmod version for all analyses

Robin Andeer
robin.andeer@gmail.com

**Comment by henrikstranneheim** [comment]
Alright!
