### ISSUE TITLE
GATK combine variants issue

### ISSUE THREAD

**Issue by robinandeer** [henrikstranneheim/MIP#124]
This is the error for case: `MIP_ANALYSIS/customers/cust009/283669/`

```
##### ERROR MESSAGE: Line 205: there aren't enough columns for line t/hds/proj/bioinfo/MIP_ANALYSIS/references_4.0/Homo_sapiens.GRCh37.d5.fasta -o /scratch/743956/283669_sorted_md_brecal_gvcf_vrecal_BOTH_normalized.vcf /scratch/743956/283669_sorted_md_brecal_gvcf_vrecal_BOTH.vcf (we expected 9 tokens, and saw 1 ), for input source: /scratch/743957/283669_sorted_md_brecal_gvcf_vrecal_BOTH.vcf
```

Found some information here:
http://gatkforums.broadinstitute.org/gatk/discussion/6247/combinegvcfs-error-message-line-116400953-there-arent-enough-columns-for-line

**Comment by henrikstranneheim** [comment]
This line in the vcf header seems to be malformed for some reason in the GATK vcf going into combine:
> ##bcftools_normCommand=norm --multiallelics -both -f /mnt/hds/proj/bioinfo/MIP_ANALYSIS/references_4.0/Homo_sapiens.GRCh37.d5.fasta -o /scratch/743956/283669_sorted_md_brecal_gvcf_vrecal_BOTH_normalized.vcf /scratch/743956/283669_sorted_md_brecal_gvcf_vrecal_BOTH.vcf

Removing that line - solves the issue. However, I do not have any idea why this one was malformed to start with. You can just rerun from the combine step or to be on the safer side restart from scratch, since we do not know if any other line has been corrupted.
